### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by hthetiot** [dilaouid/AlzheimApp#1]
Using Node 14.18.2 and npm 8.3.0, when I install the packages I get following issue:
> ERESOLVE unable to resolve dependency tree

If I use "--legacy-peer-deps" flag, it does install but then the web build fail with "react-native-dialog" with "Cannot read properties of undefined (reading 'style')" on "ViewPropTypes".

To reproduce
> npm install

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: AlzheimApp@1.0.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.x.x" from modal-react-native-web@0.2.0
npm ERR! node_modules/modal-react-native-web
npm ERR!   modal-react-native-web@"^0.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/haroldthetiot/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/haroldthetiot/.npm/_logs/2022-01-18T13_49_40_357Z-debug-0.log
```

**Comment by hthetiot** [comment]
@dilaouid I think the main issue is modal-react-native-web@0.2.0 that does not like react@"17.0.1", if you have a updated packages.json to push on main may be that will fix it, if the android/ios build work but web does not let me know and i can try to fix the web build.

**Comment by hthetiot** [comment]
https://github.com/Dekoruma/react-native-web-modal#announcement

```
Modal is now supported in react native web.

https://github.com/necolas/react-native-web/releases/tag/0.14.0

Thank you for using and supporting this library!
```

**Comment by hthetiot** [comment]
Related https://github.com/mmazzarolo/react-native-dialog/issues/131#issuecomment-1008421593

**Comment by hthetiot** [comment]
related https://miller-hodeem.medium.com/how-i-solved-the-viewproptypes-is-not-exported-from-react-native-web-dist-index-error-in-835c52e0e566

**Comment by dilaouid** [comment]
Thanks for the issue report.
Seems like it comes from `components\activities\Dictaphone\index.js`. Making the import of the `react-native-dialog` component conditional to the user platform seems to make it work. I will push a fix to the issue among an alternative modal for the web version.

**Comment by hthetiot** [comment]
Thx for update.

**Comment by dilaouid** [comment]
Issue fixed, the `react-native-dialog` component is no more. But made me saw another related issue about the web compatibility: the file import for the caretaking picture (not a big deal tho).
I am creating the quizz activity rn, so the new issue will be fixed among the new activity.

**Comment by hthetiot** [comment]
Nice did you push on main ? I will test if the fix is available.

**Comment by hthetiot** [comment]
Ok i can see the fixes, but still having issue when doing npm install that require "--legacy-peer-deps", do you have this issue also in your enviroment ?

**Comment by dilaouid** [comment]
> Ok i can see the fixes, but still having issue when doing npm install that require "--legacy-peer-deps", do you have this issue also in your enviroment ?

Sadly (or hopefully) not having this issue on Ubuntu 20.04 and Windows 10. Leaning toward it asap

**Comment by hthetiot** [comment]
Can you give me your nodeJS and NPM version?

> node -v
> npm -v

Should not be blocker for now.
