### ISSUE TITLE
Enable Github Page for https://dilaouid.github.io/AlzheimApp/

### ISSUE THREAD

**Issue by hthetiot** [dilaouid/AlzheimApp#6]
You just need to enable Github Page here : https://github.com/dilaouid/AlzheimApp/settings/pages to serve the branch https://github.com/dilaouid/AlzheimApp/tree/gh-pages on n https://dilaouid.github.io/AlzheimApp/

**Comment by dilaouid** [comment]
Thanks for the tips !!

**Comment by hthetiot** [comment]
\o/ it's live https://dilaouid.github.io/AlzheimApp/

**Comment by dilaouid** [comment]
o/\o Great job !!! Thanks alot !
